#Dockerfile contains the instructions
# used to create a dddocker Image


# this is my operating system
FROM ubuntu:22.04

#This is copying all files from my project into the Image
#In a directory called app
COPY . /app

#This is the command to run when the container Starts
CMD echo "I am a container"
